### PR TITLE
Add support for fieldsets in tile schemas

### PR DESCRIPTION
**Pull request by datakurre**
This probably still needs a test.

I don't know, why base tile form copied the whole updateWidgets from z3c.form. It might be that during the early development you still could not explicitly pass widget prefix to updateWidgets. Also, I don't know, why @garbas added form field prefixing to tile forms, though, there's probably no need to change it back anymore (plone.tile takes care that transient tiles understand prefixless values in querystring).

group_class and TileFormGroup are supported by extensible forms by plone.z3cform, which we base on.

### CODE REVIEW

**Comment by datakurre** [comment]
I got my answer. Plone 4.2 still depends on z3c.form early enough not supporting prefix-argument for update Widgets.

**Comment by michaeldunstan** [comment]
I've had a go at trying this branch with Plone 5.1b2 and mosaic 2.0.0rc4. It works fine for existing tile instances on a page. Data in the fieldsets for existing tiles can be successfully edited and saved.

But I get the following error when trying to add a new title to the page that has a fieldset:

```
ERROR Zope.SiteErrorLog 1491430429.890.39064738899 http://localhost:8080/site/page/@@add-tile/my.example.tile
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.app.tiles.browser.base, line 97, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module plone.app.tiles.browser.base, line 48, in updateWidgets
  Module z3c.form.field, line 243, in update
  Module z3c.form.datamanager, line 102, in canWrite
  Module z3c.form.datamanager, line 66, in adapted_context
TypeError: ('Could not adapt', <Document at /site/page>, <SchemaClass my.product.tiles.example.IExampleTile>)

```

**Comment by datakurre** [comment]
@michaeldunstan Thanks for the report. Could you share a minimal example tile with the issue (would help me to test this sooner)? And does this happen directly after you have selected the tile to be added (before rendering the add form for the first time) or only when you try to save the tile for the first time?

**Comment by michaeldunstan** [comment]
@datakurre This happens after selecting the title from the insert menu. Before rendering the add form.

I'll have a go at cutting out an example tile.

**Comment by datakurre** [comment]
Thanks. I realised that this may have been broken from my initial commit (and because I still need to write the test). I thought, that I have been using this already for months, but I actually have a slightly different version for myself...

**Comment by michaeldunstan** [comment]
@datakurre Here is a simple fieldset added to the RSS tile in plone.app.standardtiles that recreates the problem: https://github.com/michaeldunstan/plone.app.standardtiles/commit/906ce97a7b022574e406c6c0599498984fbd78e7

**Comment by datakurre** [comment]
@michaeldunstan Thanks. Could you try it now?

The issue was that after I started using this myself, I "fixed" this pull to also work on Plone 4.2... and broke it.

**Comment by michaeldunstan** [comment]
@datakurre That works for me now. Thank you.

**Comment by agschaid** [comment]
Hi,

I would really love to see this pulled soon. Is there anything I can do to help?

All I can deduce from the two failed checks above is that all jobs hung for 10 minutes after attempting to create the coverage report.
I'll clone and see if I can reproduce that locally...

**Comment by agschaid** [comment]
Hmmm. Ok. Test-setup failed due to `AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183`

**Comment by agschaid** [comment]
may I inquire one more time what the state of this pull-request is?
Is it abandoned? Is there anything I can do to help?

**Comment by datakurre** [comment]
Sorry. It’s waiting for me to write a test for it. I’ve been using it for quite a long time.

**Comment by petschki** [comment]
@datakurre good news. I've updated the demo tile to test your fieldset changes. All green now! This should be definitely merged and released very soon.

/cc @jensens

**Comment by petschki** [comment]
@datakurre a `3.1.0` release would be perfect! I'll update mosaic and buildout.coredev versions.cfg afterwards ...

**Comment by petschki** [comment]
or @jensens would you mind releasing `3.1.0` maybe together with plone.tiles `2.1` ?

**Comment by jensens** [comment]
@petschki will do!

**Comment by jensens** [comment]
@petschki both released!

**Comment by jensens** [comment]
@petschki please do not update Plone 5.2 - I have a PR open with other version changes and will add those 2 as well.

**Pull request merged**
