### PR TITLE
Update CI configuration

### PR DESCRIPTION
**Pull request by hvelarde**
- Update .coveragerc
- Add build for Plone 5.1
- Clean up

### CODE REVIEW

**Comment by hvelarde** [comment]
I haven't finished it :-)

**Comment by jensens** [comment]
ops, all was green and looked fine ...

**Comment by jensens** [comment]
I shall not merge from mobile phone....

**Comment by hvelarde** [comment]
yes, in fact you should not use you phone for things different than placing calls ;-)

it's ok, I add the rest of the stuff here later; merging is fine.

**Pull request merged**
