### PR TITLE
Better relationfield handling

### PR DESCRIPTION
**Pull request by danmur**
Addresses #6

### CODE REVIEW

**Comment by datakurre** [comment]
Really nice. :+1:

It was so hard to believe that this was really missing.

**Comment by gforcada** [comment]
@danmur would you mind rebasing your changes on top of the current master? Then if @datakurre is ok with it, we can merge your changes.

**Comment by danmur** [comment]
@datakurre any comments? :)

**Comment by datakurre** [comment]
This looks great to me. This week is Mephisto Sprint week, so this gets merged and released for sure.

This also reminded me that I need to remember relation values when adding CMFEditions support.

**Pull request merged**
